language: python
python:
  - "2.7"

env:
    global:
        - DB_NAME=test
        - DB_USER=root
        - DB_PASS=
        - DB_ADDR=127.0.0.1

# command to install dependencies
install: "pip install -r requirements.txt"

script:
  - nosetests

after_success:
  - codecov

services:
  - mysql

before_script:
  - mysql -e 'create database test;'
