language: python
python:
  - "2.7"

env:
    global:
        - DATABASE_URI = 'mysql+pymysql://root:@localhost:3306/test'

# command to install dependencies
install: "pip install -r requirements.txt"

script:
  - nosetests

after_success:
  - codecov

services:
  - mysql

before_script:
  - mysql -e 'create database test;'
