language: python
python:
  - "2.7"

env:
    global:
        - username = 'root'
        - password = ''
        - port = '3306'

# command to install dependencies
install: "pip install -r requirements.txt"

script:
  - nosetests

after_success:
  - codecov

services:
  - mysql

before_script:
  - mysql -e 'create database development;'
